name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Compile latex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          pre_compile: |
              apk add msttcorefonts-installer fontconfig
              update-ms-fonts
              fc-cache -f
      - name: Generate JPG from PDF
        run: sudo apt-get install poppler-utils && pdftoppm -png quality=100 resume.pdf resume
        # run: sudo apt-get install imagemagick && convert -density 300 -quality 100 resume.pdf resume.jpg

      - name: Push PDF to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upload PDF
