name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install fonts
        run: sudo apt-get install ttf-mscorefonts-installer
      - name: Generate PDF
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
